name: Test JavaScript

on:
  push:
    branches:
      - main
    paths:
      - javascript
      - .github/workflows/test-javascript.yml
  workflow_dispatch:

jobs:

  build-and-test:
    name: Build and test LocalId in JavaScript
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Jest test
        working-directory: ./javascript
        run: npm install && npm test
